# Generated by Django 5.0.7 on 2024-08-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
