# Generated by Django 5.0.7 on 2024-08-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitem_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_cost',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
